### ISSUE TITLE
.eyes wont open in Windows 10.

### ISSUE THREAD

**Issue by TimVIeweg** [hereafter/xeyes#1]
Hi, 
I purchased .eyes and Megaman pack and nothing happens when I click on .eyes or Megaman.
The window just opens and then after a second, it closes.
Hope you can help.
Kind regards
TJV.

**Comment by hereafter** [comment]
First, thanks for purchasing to support an indie.

I have drafted a how-to guide in the wiki to explain how everything works in-case there are something mis-leading in the app.

[Wiki](https://github.com/hereafter/xeyes/wiki)

I suggest 

**1. Uninstall both packages (see #7)**

**2. Download .Eyes**
Then from store, download .Eyes again, to see if it works now.
If everything is ok, then proceed to 

**3. Download Megaman Pack**
No charges if it is purchased earlier.
By the way, the latest versions are 

**.Eyes  1.3.28.0**
**Megaman Pack 1.2.6.0**

Let me know if the above helps, please get some screenshots for me to diagnose if you are still having issues, my email is tu.tong@outlook.com.

**Comment by TimVIeweg** [comment]
Hi there. I'm still having the same problem. Any ideas welcomed.
Tim V

**Comment by TimVIeweg** [comment]
Many thanks. I’ll try those steps.
Tim V.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by hereafter** [comment]
i will wait for your feedback to see if I could help further.

**Comment by TimVIeweg** [comment]
Hi I can’t see anything in event viewer .
Tim V

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by TimVIeweg** [comment]
I’m not in a rush to fix it

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by TimVIeweg** [comment]
Hi there, This is just an email to let you know the app is now working after a windows update was installed.
Regards,
Tim V.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by hereafter** [comment]
thanks, actually I made a mistake about collecting error events.

could you please first run .Clock once, then 
goto event viewer, look for 

Level: Error
Date & Time: recent about the .eyes failure
Source: "**Application Error**" and "**.NET Runtime**"

please copy the text in general here to me, I could know exactly what went wrong on your machine

still unable to replicate the issue myself.

**Comment by hereafter** [comment]
as you said in email it starts working now, I'll close this issue for now
